### ISSUE TITLE
FR: Set name and count of generated threads

### ISSUE THREAD

**Issue by Capstan** [fge/msg-simple#4]
`LoadingMessageSourceProvider` creates a `ThreadFactory` that creates threads with the default names. Consider setting the name to `MsgSimple-%d` using an `AtomicLong.getAndIncrement()` so the threads are easily attributable to their code.

**Comment by huggsboson** [comment]
Hi @Capstan I've reached out to you on linkedin to talk about setting you up to be a co-maintainer on these repos.

**Comment by huggsboson** [comment]
RE: forking.  I've had most of @fge 's repos transferred to me, but the ones that weren't I've forked into java-json-tools.

**Comment by Capstan** [comment]
@huggsboson I didn't see the LinkedIn thing, but I sent an invite back to you in case something went awry.

**Comment by singhdurgesh86** [comment]
> Hi @Capstan I've reached out to you on linkedin to talk about setting you up to be a co-maintainer on these repos.



> RE: forking. I've had most of @fge 's repos transferred to me, but the ones that weren't I've forked into java-json-tools.

Hi @huggsboson We have a question regarding license that we had opened as as issue : https://github.com/fge/msg-simple/issues/7#issue-576888334

I tried to reach out to fge with no luck. Can you please let us know whom should we reach out to for any question related to license. 

Thanks.

**Comment by Capstan** [comment]
Ah, I hadn't realized I stranded this PR in fge-land! Thanks for the reminder. This repo is derelict; please find its successor at https://github.com/java-json-tools/msg-simple and post issues there.

**Comment by Capstan** [comment]
This is fixed in https://github.com/java-json-tools/msg-simple/pull/28.
